export interface IProdutoData {
  titulo: string;
  descricao: string;
  src: string;
  imagemComMoldura: boolean;
  boolVidro: string;
  valorInicio: number;
  tiragens: number,
  vendas: number,
}

export const ProdutoData: IProdutoData[] = [
  {
    "titulo": "Dorsais",
    "descricao": "",
    "src": "artes/Dorsais.png",
    "imagemComMoldura": false,
    "boolVidro": "sim",
    valorInicio: 440.00,
    tiragens: 5,
    vendas: 0,
  },
  {
    "titulo": "Blocos e Deslizamentos",
    "descricao": "Percepção.",
    "src": "artes/blocos_e_deslizamentos_variação_II.png",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 440.00,
    tiragens: 1,
    vendas: 1,
  },
  {
    "titulo": "Fragmentos e Extensões",
    "descricao": "",
    "src": "artes/Fragmentos e Extensões.jpg",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 440.00,
    tiragens: 5,
    vendas: 0,
  },
  {
    "titulo": "Figuras",
    "descricao": "",
    "src": "artes/Figuras.jpg",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 440.00,
    tiragens: 5,
    vendas: 0,
  },
  {
    "titulo": "Posicionais",
    "descricao": "",
    "src": "artes/Posicionais.png",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 440.00,
    tiragens: 5,
    vendas: 0,
  },
  {
    "titulo": "Nascimento e Navegações",
    "descricao": "",
    "src": "artes/Nascimento e Navegações.jpg",
    "imagemComMoldura": false,
    "boolVidro": "sim",
    valorInicio: 440.00,
    tiragens: 5,
    vendas: 0,
  },
  {
    "titulo": "Desdobramentos",
    "descricao": "",
    "src": "artes/Desdobramentos.png",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 200.00,
    tiragens: 0,
    vendas: 0,
  },
  {
    "titulo": "Bandeiras",
    "descricao": "",
    "src": "artes/Bandeiras F4cm.png",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 200.00,
    tiragens: 0,
    vendas: 0,
  },
  {
    "titulo": "Arte 4/24",
    "descricao": "",
    "src": "artes/Arte 4_24.jpg",
    "imagemComMoldura": false,
    "boolVidro": "sim",
    valorInicio: 200.00,
    tiragens: 1,
    vendas: 1,
  },
  {
    "titulo": "Liquefeitos",
    "descricao": "",
    "src": "artes/Liquefeitos.png",
    "imagemComMoldura": true,
    "boolVidro": "sim",
    valorInicio: 200.00,
    tiragens: 1,
    vendas: 1,
  },
  // {
  //   "titulo": "Plaina Via Crucis",
  //   "descricao": "",
  //   "src": "artes/Plaina via crucis.jpg",
  //   "boolVidro": "sim",
  //   valorInicio: 200.00,
  //   tiragens: 2,
  //   vendas: 0,
  // },
  // {
  //   "titulo": "Grid",
  //   "descricao": "",
  //   "src": "artes/Grid.png",
  //   "boolVidro": "sim",
  //   valorInicio: 200.00,
  //   tiragens: 2,
  //   vendas: 0,
  // },
]